#!/usr/bin/env python

import sys
import time
import argparse
import requests


api_url = 'https://api.exmo.com/v1/ticker/'

def args_get():
    parser = argparse.ArgumentParser(description='Watch for cryptocurrency values to know when to sell')

    parser.add_argument('--pairs', type=str, default='BTC_USD', help='Pairs to watch for, ex. "BTC_USD,ETH_RUB"')

    parser.add_argument('--tg-token', type=str, help='Telegram Bot token')
    parser.add_argument('--tg-chat-id', type=str, help='Telegram chat ID to send notifies to')

    parser.add_argument('--period', type=int, default=3600, help='Period between sending messages')

    return parser.parse_args()

def data_get(url):
    try:
        data = requests.get(api_url).json()
    except:
        data = None
    return data

def message_form(data, pairs):
    message = []
    for pair in pairs:
        if pair in data:
            row = '*{}* avg is {}'.format(pair, data[pair]['avg'].rjust(16, ' '))
        else:
            row = '*{}* no data'.format(pair)
        message.append(row)
    return '\n'.join(message)

def message_send(tg_token, tg_chat_id, message):
    uri = 'https://api.telegram.org/bot' + tg_token + '/sendMessage'
    data = {
        'chat_id': tg_chat_id,
        'text': message,
        'parse_mode': 'Markdown',
        'disable_web_page_preview': True
    }
    res = requests.post(uri, data=data)
    return res

if __name__ == '__main__':
    if not (args.tg_token or args.tg_chat_id):
        print('Could not proceed without Telegram parameters, use --help flag to see options')
        sys.exit(0)
    args = args_get()
    pairs = args.pairs.split(',')

    while True:
        data = data_get(api_url)
        message = message_form(data, pairs)
        message_send(args.tg_token, args.tg_chat_id, message)

        time.sleep(args.period)
