#!/usr/bin/env python

import sys
import time
import argparse
import requests


api_url = 'https://api.exmo.com/v1/ticker/'

def args_get():
    parser = argparse.ArgumentParser(description='Watch for cryptocurrency values to know when to sell')

    parser.add_argument('--pairs', type=str, default='BTC_USD', help='Pairs to watch for, ex. "BTC_USD,ETH_RUB"')

    parser.add_argument('--holdings', type=str, default="", help='URL to get deals history')

    parser.add_argument('--tg-token', type=str, help='Telegram Bot token')
    parser.add_argument('--tg-chat-id', type=str, help='Telegram chat ID to send notifies to')

    parser.add_argument('--period', type=int, default=3600, help='Period between sending messages')

    return parser.parse_args()

def data_get(url):
    try:
        data = requests.get(api_url).json()
    except:
        data = None
    return data

def holdings_get(url):
    if not url:
        data = {}
    else:
        data = requests.get(url).json()
    return data

def message_form(data, pairs, holdings):
    if holdings:
        message = ['`pair    | average value   | profit`']
    else:
        message = ['`pair    | average value`']

    for pair in pairs:
        if pair in data:
            row = '`{}  {}`'.format(pair.ljust(8, ' '), data[pair]['avg'].rjust(16, ' '))

            delta_percentage = None
            if holdings and pair in holdings:
                currency_total_invested = sum([float(a['price']) * float(a['amount']) for a in holdings[pair]])
                currency_total_amount = sum([float(a['amount']) for a in holdings[pair]])

                currency_real_value = float(data[pair]['sell_price']) * currency_total_amount

                delta_percentage = round(currency_real_value / currency_total_invested * 100, 2) - 100

            if delta_percentage is not None:
                row = row[:-1] + '  {}{}%'.format('+' if delta_percentage > 0 else '', delta_percentage) + row[-1:]
        else:
            row = '`{} no data`'.format(pair)
        message.append(row)
    return '\n'.join(message)

def message_send(tg_token, tg_chat_id, message):
    uri = 'https://api.telegram.org/bot' + tg_token + '/sendMessage'
    data = {
        'chat_id': tg_chat_id,
        'text': message,
        'parse_mode': 'Markdown',
        'disable_web_page_preview': True
    }
    res = requests.post(uri, data=data)
    return res

if __name__ == '__main__':
    args = args_get()

    if not (args.tg_token or args.tg_chat_id):
        print('Could not proceed without Telegram parameters, use --help flag to see options')
        sys.exit(0)

    print('Starting ...')

    pairs = args.pairs.split(',')

    holdings = holdings_get(args.holdings)

    while True:
        data = data_get(api_url)
        message = message_form(data, pairs, holdings)
        res = message_send(args.tg_token, args.tg_chat_id, message)

        print('{} {}'.format(time.time(), res))
        time.sleep(args.period)
